### ISSUE TITLE
Hitting Play on any scene crashes the editor in Unity 2017.2

### ISSUE THREAD

**Issue by flarb** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#11]
I tried using this in Unity 2017.2 with the 2017.2 branch of HoloToolkit and it crashes the editor instantly when the play button is hit in any scene.

**Comment by JonBoyleCoding** [comment]
I have no idea if you've solved it or not, but on the new HoloToolkit (or Mixed Reality Toolkit), it mentions that you need Unity 2017.1.2 for Hololens due to a bug on Unity's end. While I've managed to get this compiled, I've yet been able to launch it on an actual hololens (about to create an issue related to that).
